# Generated by Django 4.2.8 on 2024-05-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_trackerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevices',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
