# Generated by Django 4.2.8 on 2024-05-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gpsdevices_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsdevices',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
