# Generated by Django 5.0.6 on 2024-06-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_trackerdata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevices',
            name='is_ignited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_notification',
            field=models.BooleanField(default=False),
        ),
    ]
